alk_web_homepage:
    pattern:  /
    defaults: { _controller: ALKWebBundle:Default:index }

alk_article:
    pattern:  /read/{id}
    defaults: { _controller: ALKWebBundle:Default:viewArticle }

alk_article_locale:
    pattern:   /read/{id}/in/{_locale}
    defaults:  { _controller: ALKWebBundle:Default:viewArticle, _locale: fr }
    # requirements:
    #   _locale: en|fr|ru

ALKWebBundle_article:
        resource: "@ALKWebBundle/Resources/config/routing/article.yml"
        prefix:   /article

test:
    pattern:	/test/
    defaults: { _controller: ALKWebBundle:Default:filler }