alk_web_homepage:
    pattern:  /
    defaults: { _controller: ALKWebBundle:Default:index }

alk_article:
    pattern:  /read/{id}
    defaults: { _controller: ALKWebBundle:MyArticle:show }

alk_newarticle:
    pattern: /myarticle/new
    defaults: { _controller: ALKWebBundle:MyArticle:edit }

alk_editarticle:
    pattern: /myarticle/edit/{id}
    defaults: { _controller: ALKWebBundle:MyArticle:edit }

alk_deletearticle:
    pattern: /myarticle/del/{id}
    defaults: { _controller: ALKWebBundle:MyArticle:remove }

ALKWebBundle_article:
        resource: "@ALKWebBundle/Resources/config/routing/article.yml"
        prefix:   /article

alk_article_rss:
    pattern: /myarticle/rss
    defaults: { _controller: ALKWebBundle:RSS:articleRssGenerate }