alk_web_homepage:
    pattern:  /
    defaults: { _controller: ALKWebBundle:Default:index }


ALKWebBundle_article:
        resource: "@ALKWebBundle/Resources/config/routing/article.yml"
        prefix:   /admin/article


ALKWebBundle_menuholder:
    resource: "@ALKWebBundle/Resources/config/routing/menuholder.yml"
    prefix:   /admin/menuholder


alk_article_rss:
    pattern: /page/rss
    defaults: { _controller: ALKWebBundle:RSS:articleRssGenerate }

alk_admin_logout:
    pattern: /admin/logout