
alk_article:
    pattern:  /page/{id}
    defaults: { _controller: ALKWebBundle:MyArticle:show }
    requirements:
        id: \d*

alk_newarticle:
    pattern: /page/new
    defaults: { _controller: ALKWebBundle:MyArticle:edit }

alk_editarticle:
    pattern: /page/edit/{id}
    defaults: { _controller: ALKWebBundle:MyArticle:edit }

alk_deletearticle:
    pattern: /page/del/{id}
    defaults: { _controller: ALKWebBundle:MyArticle:remove }

alk_listallarticles:
    pattern: /page/list/
    defaults: { _controller: ALKWebBundle:MyArticle:listAll, tag: "Default"}

alk_listarticleswithtags:
    pattern: /page/list/{tag}
    defaults: { _controller: ALKWebBundle:MyArticle:listAll, tag: "Default"}
    # requirements:
    #     page: \d*

article:
    pattern:  /
    defaults: { _controller: "ALKWebBundle:Article:index" }

article_show:
    pattern:  /{id}/show
    defaults: { _controller: "ALKWebBundle:Article:show" }

article_new:
    pattern:  /new
    defaults: { _controller: "ALKWebBundle:Article:new" }

article_create:
    pattern:  /create
    defaults: { _controller: "ALKWebBundle:Article:create" }
    requirements: { _method: post }

article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ALKWebBundle:Article:edit" }

article_update:
    pattern:  /{id}/update
    defaults: { _controller: "ALKWebBundle:Article:update" }
    requirements: { _method: post }

article_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ALKWebBundle:Article:delete" }
    requirements: { _method: post }
