<?php

namespace ALK\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuHolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuHolderRepository extends EntityRepository
{
}
